// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Версия среды выполнения: 14.0.0.0
//  
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DynamicFormatter.Generator.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using DynamicFormatter.Extentions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class ReferenceTypeTemplate : ReferenceTypeTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\tpublic class ");
            
            #line 8 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.className));
            
            #line default
            #line hidden
            this.Write(" :IResolver<");
            
            #line 8 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeInfo.Type.FullName));
            
            #line default
            #line hidden
            this.Write(">\r\n\t{\r\n\t");
            
            #line 10 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
foreach(var field in this.typeInfo.Fields)
	  {
		if(this.isPrivate(field))
		{

			if(this.typeInfo.IsValueType)
			{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tFunc<");
            
            #line 17 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeInfo.Type.FullName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 17 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.FieldFullName(field)));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 17 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeInfo.Type.FullName));
            
            #line default
            #line hidden
            this.Write("> Setter_");
            
            #line 17 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ValidateName(field)));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n\t\t\t");
            
            #line 19 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
}
			else
			{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tpublic Action<");
            
            #line 22 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeInfo.Type.FullName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 22 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.FieldFullName(field)));
            
            #line default
            #line hidden
            this.Write("> Setter_");
            
            #line 22 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ValidateName(field)));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n\t\t\t");
            
            #line 24 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
}
		}
		
	 }
            
            #line default
            #line hidden
            this.Write("\t\t\r\n\t\tTypeInfo typeInfo;\r\n\r\n\t\tpublic ");
            
            #line 31 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.className));
            
            #line default
            #line hidden
            this.Write("()\r\n\t\t{\r\n\t\t\tthis.typeInfo = TypeInfo.instanse(typeof(");
            
            #line 33 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeInfo.Type.FullName));
            
            #line default
            #line hidden
            this.Write("));\r\n\r\n\t\t\t");
            
            #line 35 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
foreach(var field in this.typeInfo.Fields)
			{
				if(this.isPrivate(field))
				{
							if(!this.typeInfo.IsValueType)
							{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tParameterExpression p1 = Expression.Parameter(type" +
                    "of(");
            
            #line 43 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeInfo.Type.FullName));
            
            #line default
            #line hidden
            this.Write("), \"p1\");\r\n\t\t\t\t\t\t\t\t\t\tParameterExpression p2 = Expression.Parameter(typeof(");
            
            #line 44 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.FieldFullName(field)));
            
            #line default
            #line hidden
            this.Write("), \"p2\");\r\n\r\n\t\t\t\t\t\t\t\t\t\tvar m1 = Expression.MakeMemberAccess(p1, this.typeInfo.Fie" +
                    "lds.Single(x => RuntimeHelpers.GetHashCode(x) ==");
            
            #line 46 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetHash(field)));
            
            #line default
            #line hidden
            this.Write("));\r\n\t\t\t\t\t\t\t\t\t\tBinaryExpression body = Expression.Assign(m1, p2);\r\n\t\t\t\t\t\t\t\t\t\tvar " +
                    "lambda = Expression.Lambda<Action<");
            
            #line 48 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeInfo.Type.FullName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 48 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.FieldFullName(field)));
            
            #line default
            #line hidden
            this.Write(">>(body, p1, p2);\r\n\t\t\t\t\t\t\t\t\t\tSetter_");
            
            #line 49 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ValidateName(field)));
            
            #line default
            #line hidden
            this.Write(" = lambda.Compile();\r\n\t\t\t\t\t\t\t\t}\r\n\r\n\t\t\t\t\t\t\t");
            
            #line 52 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
}
							else
							{
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tParameterExpression p1 = Expression.Parameter(typeof(");
            
            #line 57 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeInfo.Type.FullName));
            
            #line default
            #line hidden
            this.Write("), \"p1\");\r\n\t\t\t\t\t\t\t\tParameterExpression p2 = Expression.Parameter(typeof(");
            
            #line 58 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.FieldFullName(field)));
            
            #line default
            #line hidden
            this.Write("), \"p2\");\r\n\t\t\t\t\t\t\t\tParameterExpression SturctObjectParam = Expression.Variable(ty" +
                    "peof(");
            
            #line 59 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeInfo.Type.FullName));
            
            #line default
            #line hidden
            this.Write("), \"Struct\");\r\n\t\t\t\t\t\t\t\tParameterExpression retObjectParam = Expression.Variable(t" +
                    "ypeof(");
            
            #line 60 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeInfo.Type.FullName));
            
            #line default
            #line hidden
            this.Write("), \"ret\");\r\n\r\n\t\t\t\t\t\t\t\tLabelTarget returnTarget = Expression.Label(typeof(");
            
            #line 62 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeInfo.Type.FullName));
            
            #line default
            #line hidden
            this.Write("));\r\n\r\n\r\n\t\t\t\t\t\t\t\tvar assignToRet = Expression.Assign(SturctObjectParam, p1);\r\n\t\t\t" +
                    "\t\t\t\t\tvar makeMeberAccess = Expression.MakeMemberAccess(SturctObjectParam, this.t" +
                    "ypeInfo.Fields.Single(x => RuntimeHelpers.GetHashCode(x) ==");
            
            #line 66 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetHash(field)));
            
            #line default
            #line hidden
            this.Write(@"));

								var assign = Expression.Assign(makeMeberAccess, p2);
								var assingnToResult = Expression.Assign(
																retObjectParam,
																(SturctObjectParam));

								GotoExpression returnExpression = Expression.Return(returnTarget,
																				retObjectParam, typeof(");
            
            #line 74 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeInfo.Type.FullName));
            
            #line default
            #line hidden
            this.Write(@"));

								LabelExpression returnLabel = Expression.Label(returnTarget, retObjectParam);

								BlockExpression block = Expression.Block(
																		new ParameterExpression[] { SturctObjectParam, retObjectParam },
																		assignToRet,
																		assign,
																		assingnToResult,
																		returnExpression,
																		returnLabel);
								var lambda = Expression.Lambda<Func<");
            
            #line 85 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeInfo.Type.FullName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 85 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.FieldFullName(field)));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 85 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeInfo.Type.FullName));
            
            #line default
            #line hidden
            this.Write(">>(block, p1, p2);\r\n\t\t\t\t\t\t\t\tSetter_");
            
            #line 86 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ValidateName(field)));
            
            #line default
            #line hidden
            this.Write(" = lambda.Compile();\r\n\t\t\t\t\t\t\t}\r\n\r\n\t\t\t\t\t\t\t");
            
            #line 89 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
}
					}
			}
			
            
            #line default
            #line hidden
            this.Write("\r\n\t\t}\r\n\r\n\t\tpublic object instanse(int offset, DynamicBuffer buff, Dictionary<int," +
                    " object> referenceMaping)\r\n\t\t{\r\n\t\t\tbyte[] buffer = buff.CurrentBuffer;\r\n\t\t\tvar e" +
                    "ntity = (");
            
            #line 99 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeInfo.Type.FullName));
            
            #line default
            #line hidden
            this.Write(")FormatterServices.GetSafeUninitializedObject(typeof(");
            
            #line 99 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeInfo.Type.FullName));
            
            #line default
            #line hidden
            this.Write("));\r\n\t\t\toffset++;\r\n\t\t\t");
            
            #line 101 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
foreach(var field in this.typeInfo.Fields)
			{
				if(this.isPrimitive(field))
				{
					if(this.isPrivate(field))
					{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t");
            
            #line 107 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
if(this.typeInfo.IsValueType)
						{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\tentity = Setter_");
            
            #line 109 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ValidateName(field)));
            
            #line default
            #line hidden
            this.Write(".Invoke(entity,BaseConvertor.Get");
            
            #line 109 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetTypePrefix(field)));
            
            #line default
            #line hidden
            this.Write("(buffer, offset));\r\n\t\t\t\t\t\t");
            
            #line 110 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
}
						else
						{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\tSetter_");
            
            #line 113 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ValidateName(field)));
            
            #line default
            #line hidden
            this.Write(".Invoke(entity,BaseConvertor.Get");
            
            #line 113 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetTypePrefix(field)));
            
            #line default
            #line hidden
            this.Write("(buffer, offset));\r\n\t\t\t\t\t\t");
            
            #line 114 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
}
					}
					else
					{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\tentity.");
            
            #line 118 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ValidateName(field)));
            
            #line default
            #line hidden
            this.Write(" = BaseConvertor.Get");
            
            #line 118 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetTypePrefix(field)));
            
            #line default
            #line hidden
            this.Write("(buffer, offset);\r\n\t\t\t\t\t");
            
            #line 119 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
}
					}
			  else if(field.FieldType == typeof(string))
			  {
            
            #line default
            #line hidden
            this.Write("\t\t\t\tstring ");
            
            #line 123 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ValidateName(field)));
            
            #line default
            #line hidden
            this.Write(" = DesirializeString(offset,buff,referenceMaping);\r\n\t\t\t\t");
            
            #line 124 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
if(this.isPrivate(field))
				{
					if(this.typeInfo.IsValueType)
					{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\tentity = Setter_");
            
            #line 128 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ValidateName(field)));
            
            #line default
            #line hidden
            this.Write(".Invoke(entity,");
            
            #line 128 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ValidateName(field)));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\t\t");
            
            #line 129 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
}
					else
					{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\tSetter_");
            
            #line 132 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ValidateName(field)));
            
            #line default
            #line hidden
            this.Write(".Invoke(entity,");
            
            #line 132 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ValidateName(field)));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\t\t");
            
            #line 133 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
}
				}
				else
				{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tentity.");
            
            #line 137 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ValidateName(field)));
            
            #line default
            #line hidden
            this.Write("  = ");
            
            #line 137 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ValidateName(field)));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t");
            
            #line 138 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
}
			 }
			 else
			 {
            
            #line default
            #line hidden
            this.Write("\t\t\t\tshort ptrFor");
            
            #line 142 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ValidateName(field)));
            
            #line default
            #line hidden
            this.Write(" = BaseConvertor.GetShort(buffer,offset);\r\n\r\n\t\t\t\t");
            
            #line 144 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.FieldFullName(field)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 144 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ValidateName(field)));
            
            #line default
            #line hidden
            this.Write("_Result =(");
            
            #line 144 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.FieldFullName(field)));
            
            #line default
            #line hidden
            this.Write(") TypeResolveFactory.ResolveDesirialize(\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttypeof(");
            
            #line 145 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.FieldFullName(field)));
            
            #line default
            #line hidden
            this.Write("),\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tptrFor");
            
            #line 146 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ValidateName(field)));
            
            #line default
            #line hidden
            this.Write(",\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tbuff,\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\treferenceMaping);\r\n\r\n\t\t\t\t");
            
            #line 150 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
if(this.isPrivate(field))
				{
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t");
            
            #line 153 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
if(this.typeInfo.IsValueType)
					{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\tentity = Setter_");
            
            #line 155 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ValidateName(field)));
            
            #line default
            #line hidden
            this.Write(".Invoke(entity,");
            
            #line 155 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ValidateName(field)));
            
            #line default
            #line hidden
            this.Write("_Result);\r\n\t\t\t\t\t");
            
            #line 156 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
}
					else
					{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\tSetter_");
            
            #line 159 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ValidateName(field)));
            
            #line default
            #line hidden
            this.Write(".Invoke(entity,");
            
            #line 159 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ValidateName(field)));
            
            #line default
            #line hidden
            this.Write("_Result);\r\n\t\t\t\t\t");
            
            #line 160 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
}

				}
				else
				{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tentity.");
            
            #line 165 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ValidateName(field)));
            
            #line default
            #line hidden
            this.Write("  = ");
            
            #line 165 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ValidateName(field)));
            
            #line default
            #line hidden
            this.Write("_Result;\r\n\t\t\t\t");
            
            #line 166 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
}

			 }
            
            #line default
            #line hidden
            this.Write("\t\t\t  offset += ");
            
            #line 169 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetSizeInBuffer(field)));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t");
            
            #line 170 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 172 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
if(this.typeInfo.IsValueType)
			{
				
            
            #line default
            #line hidden
            this.Write("return (object)entity;");
            
            #line 174 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"

			}
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 177 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"
if(!this.typeInfo.IsValueType)
			{
				
            
            #line default
            #line hidden
            this.Write("return entity;");
            
            #line 179 "C:\Users\kkovalenko\Documents\DynamicFormatter\DynamicFormatter\DynamicFormatter\Generator\Templates\ReferenceTypeTemplate.tt"

			}
            
            #line default
            #line hidden
            this.Write(@"		}

		public unsafe string DesirializeString(int offset, DynamicBuffer buffer, Dictionary<int, object> referenceMaping)
		{
			fixed (byte* buf = buffer.CurrentBuffer)
			{
				short position = offset == 0 ? (short)0 : *(short*)(buf + offset);
				if (position == -1)
				{
					return null;
				}
				if (referenceMaping.ContainsKey(position))
				{
					return referenceMaping[position] as string;
				}
				int lenght = *(int*)(buf + position);

				fixed (char* charP = new char[lenght])
				{
					int bytesForCopy = sizeof(char) * lenght;
					byte* source = (buf + position + sizeof(int));
					Buffer.MemoryCopy(source, charP, bytesForCopy, bytesForCopy);
					return new String(charP);
				}
			}
		}
	}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class ReferenceTypeTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
